config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

    root 'homes#index'
    resources :dashboards do
      collection do
        get 'get_user_emails'
        get 'fetch_user_detail'
        get 'user_detail'
      end
    end

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.user_email(search)
		if search
	  		search_condition = "%" + search + "%"
	  		where("fname like ? or email like ? or lname like ? or emp_id like ?", search_condition, search_condition, search_condition, search_condition).map(&:email)
	    else
			# 	all
		end 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def index
		
	end

	def get_user_emails
		@result = User.user_email(params[:term])
		render :json => @result 
	end

	def fetch_user_detail
		search_input = params[:search].split(",").uniq
  		@list_user = User.where(email: search_input)
	end

	def user_detail
		@email = params[:email].split(",").uniq
		@theme = params[:theme]
		@email.each do |email_addr|
		 UserMailer.delay.thanks_template(email_addr,@theme)
		end
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index 

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  skip_before_filter :verify_authenticity_token, :only => :send_mail
	def index
		# @user_email = User.all.uniq.map(&:email)
		@user = User.all
		@users = User.new
	end

	def send_mail
		@to = params[:to_addr]
		@email= params[:email]
		@message = params[:message]
		@timestamp =params[:timestamp]
		UserMailer.card_template(@to,@email,@message,@timestamp).deliver
	end

	private

	def user_params
		params.require(:user).permit(:to, :from,:message,:timestamp)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/_user_list.html.erb
<% if @list_user.present? && !@list_user.blank? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @list_user.each do |card| %>
        <tr>  
          <td><%= card.fname %></td>
          <td><%= card.lname %></td>
          <td><%= card.email %></td>
          <td>
          <img alt="Delete" class="delete_user" id="delete_<%= card.emp_id%>" onclick="remove_user('<%= card.email %>','<%= card.emp_id %>');" src="/assets/close.png">
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/dashboards/fetch_user_detail.js.erb
$(".user_list").html("<%=escape_javascript(render 'dashboards/user_list')%>");

app/views/dashboards/index.html.erb
<div class="headerSec">
	Welcome Anupriya
</div>
<div class="search_box">
	<div class="ui-widget">
		<p>
			<label for="Employee_Search" class="labelName">Employee_Search</label>
			<input type="text" name="search" id="search_user_email" autocomplete="off" class="email ui-autocomplete-input">
        	<input type="hidden" name="user_emails" id="selected_emails" value=''/>
    		<input id="add_user" type="submit" value="Add">
    		<span id="search_usr_error" style="display:none;"></span>
 		</p>
	</div>
	<div class="user_list">

	</div>
	<div class="theme_list">
        <label><input type="radio" name="themes" value="theme1"> Theme1</label><br><br>
        <label><input type="radio" name="themes" value="theme2"> Theme2</label><br><br>
        <label><input type="radio" name="themes" value="theme3"> Theme3</label><br>
    </div>
    <div class="theme_layout">
    	<div class="theme1 box">
    		<%= image_tag "thank.jpg", alt: "Theme1", width:"150", height: "150"%>
    		Thank You for your support on fixing the Code Issue.</div>
    	<div class="theme2 box">
    		<%= image_tag "thanks.jpg", alt: "Theme2", width:"150", height: "150"%>
    		Thank You for your support on fixing the Code Issue.</div>
    	<div class="theme3 box">
    		<%= image_tag "thank-you.jpg", alt: "Theme3" , width:"150", height: "150"%>
    		Thank You for your support on fixing the Code Issue.</div>
    </div>
</div>
<br><br>
<div class="form-submit">
	<input type="submit" value="Thanks A Bunch" class="thanks-a-bunch">
	<input type="reset" value="Reset" class="reset">
	<input type="button" value="Back" onclick="history.back();"> 
</div>
<script type="text/javascript">
	/*autocomplete search for email*/
    jQuery('.email').autocomplete({
	    autoFocus: true,
	    source: "/dashboards/get_user_emails",
	    messages: {
	        noResults: '',
	        results: function() {}
	    },
	    minLength: 1,
	    focus: function (event, ui) {
	        jQuery(event).val(ui.item.label);
	    },
	    select: function (event, ui) {
	        jQuery(event).val(ui.item.label);
	    }
	});
	/*Add multiple users from search result*/
	jQuery("#add_user").click(function(){
		/*check if email is empty*/
		var errorFlag = false;  
		email = jQuery("#search_user_email");
  		var emailRegEx = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
		if (email.val()==null || email.val().trim()=="") {
        $("#search_user_email").css("border","1px solid #fc8989");
        $("#search_usr_error").html("Email is mandatory");
        $("#search_usr_error").css("display","block");
        errorFlag = true;
    	}
    	else if (!(email.val().match(emailRegEx))){
		$("#search_user_email").css("border","1px solid #fc8989");
		$("#search_usr_error").html("Email is invalid");
    	$("#search_usr_error").css("display","block");
		errorFlag = true;
		} else {
		$("#search_usr_error").css("display","none");
		$("#search_user_email").css("border","1px solid");
		}
		/* Added users email listing */
        var email = jQuery("#search_user_email").val();
        var selected_users = jQuery("#selected_emails").val();
        var selected_emails = [];
        if(selected_users == ""){
            selected_emails.push(email);
            jQuery("#selected_emails").val(selected_emails);
        }else{
            selected_emails.push(selected_users);
            selected_emails.push(email);
            jQuery("#selected_emails").val(selected_emails);
        }
        var final_users =jQuery("#selected_emails").val();
        jQuery.ajax(
            {
                url : "/dashboards/fetch_user_detail",
                type: "GET",
                data : {search: final_users} ,
                dataType: "script",
                success:function(data){}
            });
	});
	/*Delete selected user functionality */
	function remove_user(remove_email, id){
	    jQuery("#delete_"+id).closest('tr').remove();
	    var selected_users = jQuery("#selected_emails").val();
	    var email_array = selected_users.split(",")
	    var index = jQuery.inArray(remove_email, email_array);
	    if (index > -1) { email_array.splice(index, 1);}
	    jQuery("#selected_emails").val(email_array.join(","));
  	}
  	/*theme selection*/
	jQuery('input[type="radio"]').click(function(){
	    if(jQuery(this).attr("value")=="theme1"){
	        jQuery(".box").hide();
	        jQuery(".theme1").show();
	    }
	    if(jQuery(this).attr("value")=="theme2"){
	        jQuery(".box").hide();
	        jQuery(".theme2").show();
	    }
	    if(jQuery(this).attr("value")=="theme3"){
	        jQuery(".box").hide();
	        jQuery(".theme3").show();
	    }
	});
	/* Reset functionality */
	jQuery( ".reset" ).click(function() {
  		jQuery('#search_user_email').val('');
  		jQuery('.user_list').html('');
  		jQuery('input:radio[name=themes]').attr('checked', false);
  		jQuery('.theme1,.theme2,.theme3').html('');
  		jQuery(".box").css("display","none");
	});
	/* Mail functionality */
	jQuery(".thanks-a-bunch").click(function(){
		var selected_emails = jQuery("#selected_emails").val();
		var theme_id = jQuery("input[name='themes']:checked").val();
		console.log(selected_emails);
		console.log(theme_id);
	    jQuery.ajax(
        {
            url : "/dashboards/user_detail",
            type: "GET",
            data : {email: selected_emails, theme: theme_id} ,
            dataType: "script",
            success:function(data){}
        });
	});
</script>

app/views/dashboards/user_detail.html.erb
Mail sent successfully

app/views/homes/index.html.erb
<h5><%= link_to "Thanks A Bunch", dashboards_path%></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ThanksABunch" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ThanksABunch</a>
        <!-- <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%#= link_to "Link1", "/path1"  %></li>
            <li><%#= link_to "Link2", "/path2"  %></li>
            <li><%#= link_to "Link3", "/path3"  %></li>
          </ul>
        </div> -->
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <!-- <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> --><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Alten CalsoftLabs 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/index.html.erb
<!-- Including CSS & jQuery Dialog UI Here--><!-- 
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/ui-darkness/jquery-ui.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
<div class="container">
	<div class="main">
		<div id="dialog" title="Thanks A Bunch">
			<form action="send_mail" method="post">
				<label>To:</label>
				<input id="to_addr" name="to_addr" type="text">
				<label>From:</label>
				<input id="email" name="email" type="text">
				<label>Message:</label>
				<textarea rows="4" cols="25" name="message"  id="message" placeholder="Enter Your Message..."></textarea>
				<label>Timestamp:</label>
				<input type="time" name="timestamp" step="1"><br><br>
				<input id="submit" type="submit" value="Thanks">
			</form>
		</div> -->
	<!-- <label>
		<input type="radio" value="card1" />Theme1</label><br>
	<label>
		<input type="radio" value="card2" />Theme2</label><br>
	<label> -->
<!-- 	<input id="button" type="button" value="Open Card">
	</div>
</div> -->
== begin
<script type="text/javascript">
$(document).ready(function() {
	/*Dialog box*/
	$(function() {
		$("#dialog").dialog({
			autoOpen: false
		});
		$("#button").on("click", function() {
			$("#dialog").dialog("open");
		});
	});
	// Validating Form Fields.....
	$("#submit").click(function(e) {
		var email = $("#email").val();
		var to_addr = $("#to_addr").val();
		var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
		if (email === '' || to_addr === '') {
			alert("Please fill all fields...!!!!!!");
			e.preventDefault();
		} else if (!(email).match(emailReg)) {
			alert("Invalid Email...!!!!!!");
			e.preventDefault();
		} else {
			// alert("Form Submitted Successfully......");
		}
	});
	/*email autocomplete search*/
	var availableTags=new Array();
	<%if !@user.nil?%>
		<% @user.each do |auto_complete|%>
			availableTags.push('<%=auto_complete.email%>');
		<%end%>
	<%end%>
	$("#to_addr" ).autocomplete({
		source: availableTags
	});
	/*Placeholder focus and blur*/
	$('input,textarea').focus(function(){
   		$(this).data('placeholder',$(this).attr('placeholder'))
   		$(this).attr('placeholder','');
	});
	$('input,textarea').blur(function(){
   		$(this).attr('placeholder',$(this).data('placeholder'));
	});
	/*fade out background*/
	$(".ui-widget-overlay").attr('style','background-color: #000; opacity:1; z-index:1000;');
});
</script>
== end

app/views/users/send_mail.html.erb
<h5> Form submitted successfully</h5>